version: "3.7"
services:
  spark-master:
    image: zarusz/spark-dotnet-master:latest
    container_name: spark-dotnet-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    networks: 
      spark-network:
        ipv4_address: 10.5.0.2
    volumes:
       - C:/Users/tomasz/dev/container/spark/apps:/opt/spark-apps
       - C:/Users/tomasz/dev/container/spark/data:/opt/spark-data
       - C:/Users/tomasz/dev/container/spark/logs:/spark/logs
    environment:
      - "SPARK_LOCAL_IP=spark-master"
networks:
  spark-network:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 10.5.0.0/16
